name: Setup Nexus Infrastructure

on:
  workflow_dispatch:

jobs:
  setup-nexus:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get Nexus IP
        id: nexus
        run: echo "public_ip=$(terraform output -raw nexus_public_ip)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible dependencies
        run: pip install -r ../ansible/requirements.txt

      - name: Write SSH key to file
        run: echo "${{ secrets.NEXUS_KEY_PEM }}" > nexus-key.pem && chmod 400 nexus-key.pem

      - name: Run Ansible playbook
<<<<<<< HEAD
        TYPE_HERRE
=======
        run: ansible-playbook -i "${{ steps.nexus.outputs.public_ip } ," --private-key nexus-key.pem -u ec2-user ../ansible/playbook.yml
>>>>>>> 506d9787c57826a81ce64853223b6c56e5148ef9
        env:
          NEXUS_ADMIN_PASSWORD: ${{ secrets.NEXUS_ADMIN_PASSWORD }}
          NEXUS_CI_USER_PASSWORD: ${{ secrets.NEXUS_CI_USER_PASSWORD }}
